-- models/staging/stg_customers.sql
SELECT
    CUSTOMER_ID,
    INITCAP(FIRST_NAME) AS FIRST_NAME,
    INITCAP(LAST_NAME) AS LAST_NAME,
    DOB,
    SIGNUP_DATE,
    ADDRESS,
    LOWER(EMAIL) AS EMAIL
FROM LENDABLE_RAW.CUSTOMERS
